package com.example.p4_watre_loic.api;

import com.example.p4_watre_loic.réu.Reu;

import java.util.List;

import static com.example.p4_watre_loic.api.FakeApiServiceGenerator.generateReunions;

public class FakeApiService implements ApiService {

    private List<Reu> Reunions = generateReunions();

    /**
     * Return a list of {@link Reu}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<Reu> getReunions() {
        return Reunions;
    }

    /**
     * Delete a {@link Reu} from the {@link FakeApiService#Reunions} list.
     */
    @Override
    public void deleteReu (Reu reu) {
        Reunions.remove(Reunions);
    }
}
